### ISSUE TITLE
turn shapefiles into geojson in browser

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#10]
using https://github.com/calvinmetcalf/shapefile-js

**Comment by daguar** [comment]
:+1:

**Comment by svmatthews** [comment]
Should probably just use https://github.com/mapbox/leaflet-omnivore to cover all of our bases quickly

**Comment by npeihl** [comment]
:+1: 

Very few of my users have ever heard of geojson. Shapefiles are well-known though.

**Comment by svmatthews** [comment]
Yah, I think it's unlikely that people will have `geoJson` files lying around for them to edit. I'll make sure this becomes a priority during our sprint next week!

**Comment by npeihl** [comment]
Cool. Looking forward to meeting you at the Spring Fling.

**Comment by svmatthews** [comment]
Likewise! :dancer:

**Comment by lyzidiamond** [comment]
Pssssssst: https://github.com/daguar/shapefile-to-webmap /cc @daguar

**Comment by lyzidiamond** [comment]
Oh snaps I should read comments before I post them... sorry to be repetitive :fearful:

**Comment by npeihl** [comment]
Unless I'm missing something, leaflet-omnivore doesn't appear to handle shapefiles. Perhaps [leaflet-shapefile](https://github.com/calvinmetcalf/leaflet.shapefile) would work.

**Comment by svmatthews** [comment]
@npeihl you are correct. I think the shapefile piece will have to be different but including omnivore is going to be part of the same process.

@aaronr what was your work-around for using modules without `require()`? Would it be worth adding browserify #8 so we can get these issues out of the way?

**Comment by mapsam** [comment]
Thanks to @jczaplew for knocking this one out!

![dropchop-loadshapefile](https://cloud.githubusercontent.com/assets/1943001/10544600/03a60d54-73ea-11e5-9d28-256a9f28c378.gif)
