### ISSUE TITLE
grunt-contrib-* doesn't install on Windows

### ISSUE THREAD

**Issue by mojodna** [cugos/dropchop#102]
`npm install` picks up most of the dev dependencies but not all.  Interestingly, it's just the grunt-contrib modules that are missing.  Installing them individually after-the-fact works for the most part (with the occasional test or `sass` problem).

**Comment by eldang** [comment]
I've actually found something similar on at least one Mac OS install: we had to explicitly 'install -g grunt-cli` while everything else was taken care of by `npm install`.

**Comment by svmatthews** [comment]
@eldang I added the `grunt-cli` piece to the [wiki](https://github.com/cugos/dropchop/wiki/Installing-the-Project) for now. Wonder if there is a workaround here?

**Comment by eldang** [comment]
@svmatthews I feel like there has to be, but I'm afraid I just don't know very much about npm. This is actually the second project I've used for which "manually install grunt-cli even though we have an npm install step later" is in the setup instructions, so I do think it's something special about that package.

**Comment by eldang** [comment]
On further reading, I see two relevant things:

One is that `grunt` is always supposed to be installed locally, while `grunt-cli` is intended to be installed globally, and AFAIK `npm install` only installs things locally (though again I don't know this tool well).  This thread gets dangerously close to programmer holy war territory, but is also quite illuminating: https://github.com/gruntjs/grunt-cli/issues/10

The other is that there does seem to be a workaround, allowing grunt-cli to be used with a local install via `npm install`, if you add another section to `package.json`: https://www.npmjs.com/package/grunt-cli#installing-grunt-cli-locally

**Comment by eldang** [comment]
Oh, but hang on: it looks like you've already put the script called for by https://www.npmjs.com/package/grunt-cli#installing-grunt-cli-locally into `package.json`. In that case I'm not sure what else to try.

**Comment by svmatthews** [comment]
Would it be insane to add a `postinstall` script to the `package.json` that does `npm install -g grunt-cli`? It might require `sudo npm install -g grunt-cli` ...

**Comment by svmatthews** [comment]
There's also the option to totally ditch `grunt` and move to `gulp` ...

**Comment by mapsam** [comment]
The [`alpha`](https://github.com/cugos/dropchop/tree/alpha) branch will introduce `gulp` and remove the `Grunt` dependency entirely. Gulp is a bit tighter and doesn't require a separate `-g` install for the command line interface.

**Comment by eldang** [comment]
:+1:
Does it need testing?  I'm happy to poke at it, now or later.

**Comment by mapsam** [comment]
Definitely! Things are not very stable right now, in regards to dependencies, but feel free to pull down the `alpha` branch and after running `npm install` you should be able to run `gulp` to build the site and load it on a server. Might need to `gulp vendor` to get some dependencies bundled as well.

**Comment by mapsam** [comment]
No longer using `Grunt`, which means install does not require installing the `grunt-cli` toolkit any longer. We are now using `gulp` which installs nicely with `npm install`.

**Comment by mapsam** [comment]
@eldang all of the `alpha` branch has been merged into `master` so feel free to give it a whirl and let me know if you run into any issues.

**Comment by mapsam** [comment]
Updated install instructions are here: https://github.com/cugos/dropchop/wiki/Installing-the-Project
