### ISSUE TITLE
Pressing enter in operation form redirects page

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#113]
If you select an input field on an operation's intermediary form, the page redirects to the same URL with query parameters representing the forms inputs.  This results in the user losing all data and progress.

![bug](https://cloud.githubusercontent.com/assets/897290/7646836/b22f9350-fa86-11e4-92d4-083d4b0b9c3a.gif)

**Comment by alukach** [comment]
Not sure what to do about this one.  It may be possible to override the inherit handler of the "enter" command on a form?

ps This is using Chrome Version 42.0.2311.135 (64-bit) on Mac OSX

**Comment by svmatthews** [comment]
Good eye - we can override the enter button to `preventDefault()` and then run the submit function.
