### ISSUE TITLE
Add Layer / Remove Layer buttons

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#117]
I think it'd be helpful to have an "add layer" and "remove layer" button.

**Add Layer(s)**
- When clicked, opens a file selection input box. Maybe I don't use a mouse? Maybe I don't like using drag/drop for file?
- This is where future options like "add layer from URL" would live. In this case, when clicked, would open a menu with "Add from computer", "Import from URL", etc.

**Remove Layer(s)**
- Pretty self explanatory, when pressed it removes all selected layers from layerlist, map, and memory.

I see these two buttons living at the bottom of the layerlist, as :heavy_plus_sign: and :heavy_minus_sign: symbols.  Not married to that UI, just the first that I thought of.  Hoping we can stay away from cramming too much into the menu-bar.

**Comment by svmatthews** [comment]
Sounds good to me! Will have to essentially hook into the `fileReader` and create a `removeLayer` hook.
