### ISSUE TITLE
Update to Dropchop from DNC

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#120]
Now that this project has been officially renamed to "Dropchop" - let's make sure the source code reflects that. Requires us to rename a bunch of `L.Class`s

**Comment by svmatthews** [comment]
This has been completed in the README with #119

**Comment by mapsam** [comment]
@alukach do you think this can just be `Dropchop` instead of `DC` ?

**Comment by alukach** [comment]
I see no reason why not.
