### ISSUE TITLE
An 'updating' notification

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#127]
PR #123 altered operations to be asynchronous.  As we move towards operations that may have a longer runtime (such as loading large files via AJAX, producing raster data, etc), it will become important to indicate that the operation has started and is currently running.  With operations like loading files, it will be possible to determine the percentage complete for the operation.  

It would be nice to have the ability to create a long-standing notification, push updates to the notification (such as percentage complete), and then close the notification.  If percentage is not applicable, the notification could have some animated spinner or ellipses, indicating the ongoing operation.

This logic would likely be called in the operation's executor and close the notification when the callback is run.

**Comment by mapsam** [comment]
Got this added in the `alpha` branch. Doesn't include anything special like loading time though :stuck_out_tongue_closed_eyes: 

Turn it on/off by running:

```javascript
dc.util.loader(true) // turns it on
dc.util.loader(false) // turns it off
```

![dropchop-loader](https://cloud.githubusercontent.com/assets/1943001/10066957/b94328ea-624c-11e5-9dd5-9ab840e167c6.gif)

**Comment by alukach** [comment]
This looks good, but a small word of caution: I find that locking the user out of the UI with a loading screen can be a bit of a drag. A browser is likely capable of still being able to do stuff while things are loading (especially for io intensive operations like hitting an external api), cpu performance probably wouldn't be an issue. It would be nice to be able to queue up a few layers from overpass and then have them appear as they come in.

Maybe we should go with the current implementation for now and I'll make another issue for making them non-blocking?

**Comment by mapsam** [comment]
Agreed - I think we'll have to introduce some sort of web worker so we can make sure we don't lock up the browser for things like this. What's your favorite worker library?

**Comment by alukach** [comment]
To be honest, I know absolutely nothing about web workers. I'll do some research in my spare time. I just assumed that, thanks to JavaScript's asynchronous nature, best practice was to just start an operation and let the callback take care of the results.

**Comment by mapsam** [comment]
I would imagine that's the underlying concept of workers - but I also do not know much about them. Ran into https://github.com/calvinmetcalf/catiline when looking at shapefile uploads for #10
