### ISSUE TITLE
Shift + Select offset

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#129]
It appears that, when holding `Shift` between two selections of layerlist items, the outcome selection is offset by 1 (ie, selects the correct number of layer, but selects 1 above what it should and 1 short of what it should on the bottom).

@mapsam any ideas as to why this could be?

![offset-select](https://cloud.githubusercontent.com/assets/897290/7895570/737e558c-0653-11e5-872f-d4b607219748.gif)

**Comment by mapsam** [comment]
Weird that this started happening - updated the calculations! 

![dropchop-selectfix](https://cloud.githubusercontent.com/assets/1943001/7929573/720d1784-08b4-11e5-95ff-2eaab98221c7.gif)
