### ISSUE TITLE
Add 'my location' to map

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#144]
A user should be able to add their location as a layer to the map.

**Comment by lyzidiamond** [comment]
Ooh, this is a neat idea. Relevant: https://github.com/domoritz/leaflet-locatecontrol

**Comment by mapsam** [comment]
![dropchop-location](https://cloud.githubusercontent.com/assets/1943001/10437367/27ba0722-70f2-11e5-9f25-851c97f908a8.gif)

**Comment by mapsam** [comment]
Muchas gracias @jonahadkins

**Comment by alukach** [comment]
Awesome, I love this feature.  So many fun possibilities are going to come out of this layer.

**Comment by mapsam** [comment]
![scheming](https://cloud.githubusercontent.com/assets/1943001/10438522/b3550ac8-70f9-11e5-8344-3c0485dfa13c.gif)

**Comment by jonahadkins** [comment]
woah! it looks awesome! :raised_hands: :raised_hands: :raised_hands:
