### ISSUE TITLE
Update URL when adding / removing operations from URLs/gists

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#146]
When a layer is added to DropChop via URL or Gist (using the Add menu), the `window.location.pathname` should be updated to reflect the new layer.

When a layer that was added via URL or Gist is removed from DropChop, the `window.location.pathname` should be updated to reflect the removed layer. This may rely on the completion of #140.

I see this as having two gains:

1. Better maintain state between sessions. This is actually somewhat minor if the operations are saved between sessions (cached or saved via other service).
2. Improve awareness of the ability to append `gist`, `url`, or `stream` to the URL to load data.

**Comment by jczaplew** [comment]
I think this was closed with #204. Can you please confirm it's the same?

**Comment by alukach** [comment]
Oops, slow reply, looks to be all taken care of, nice work @jczaplew!
