### ISSUE TITLE
build "view extent" button

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#15]
this button would zoom the map to the extent of all of the visible layers

**Comment by svmatthews** [comment]
Extent option created by @aaronr in #36 that does this for the time being. Seems like we have three different "menu categories" right now:

1. `File` includes save operations, load, export, etc.
1. Defaults which can be turned on and off, and might include app operations (non data-affecting operations)
1. geoprocessing operations that edit and create new data

**Comment by mapsam** [comment]
Resolved in #170 

![dropchop-extent](https://cloud.githubusercontent.com/assets/1943001/9834861/540e9c92-5983-11e5-8b61-7cd004955110.gif)

**Comment by mapsam** [comment]
Expanded this one step further. If no layers are selected the map expands to the entire feature layer bounds. If layers are selected, the map only expands to the extent of all of them - thanks to @aaronr for the `bounds.extend()` trick!

![dropchop-extend-all-or-some](https://cloud.githubusercontent.com/assets/1943001/9835309/e85b9a74-5999-11e5-9c4f-795102822016.gif)
