### ISSUE TITLE
Package as Electron app?

### ISSUE THREAD

**Issue by npeihl** [cugos/dropchop#157]
Since dropchop is now using Browserify, is it possible to package it as an Electron app? I've not worked with Electron before, but it seems like a good candidate.

**Comment by alukach** [comment]
I believe that building a Dropchop app via [Electron](https://github.com/atom/electron) or [NW.js](https://github.com/nwjs/nw.js/) is totally possible. The idea is fun as well. I haven't yet run into a use-case for this, though. 

This issue may be a good place to start that conversation. @npeihl, do you have any usages for Dropchop that aren't available as currently designed (without an desktop component)?

One difficulty that I see us running into would be the fact that we rely on hosted maptiles. This binds us to the requiring internet access. To get around this, we could package the app with tiles (I imagine that this is possible via Electron or NW.js?). The downside to that would be the storage size of those tiles. Instead, we could package the app with a set of vector tiles which would take less space, but I believe that this would require us to adopt MapboxGL which may reduce the number of people who could use the app. In either case, we would probably have to roll out own tiles as I believe shipping an app with Mapbox tiles is a no-no. So yeah, there are challenges but I believe we can get around them.

**Comment by npeihl** [comment]
I don't have a full case for it yet either. I think @mapsam had mentioned either at the Spring Fling or somewhere else that he thought dropchop could be an offline app at some point. And I like the idea of using Electron's native dialog boxes to be able to load files rather than just drag-n-drop. Perhaps this would be useful for #10. 

I agree that going to Mapbox GL is out of scope for dropchop. And rolling our own tiles doesn't sound like much fun. And even though [Tilemaker](https://github.com/systemed/tilemaker) looks interesting, it isn't a JavaScript solution and doesn't fit with dropchop.

I don't think packaging with Electron is completely a half-baked idea, but perhaps this could be shelved as a far-off-in-the-future concept. It's an interesting discussion, but maybe let our children's children develop it.   :older_woman: :older_man: 

If you agree that we should shelve it, I'm fine with closing this issue.

**Comment by alukach** [comment]
> And I like the idea of using Electron's native dialog boxes to be able to load files rather than just drag-n-drop.

Have you had a chance to check out the 'Add' button?

![addbutton](https://cloud.githubusercontent.com/assets/897290/7829362/3ded55d2-03fe-11e5-86a2-7ba5d7609f88.gif)

> And rolling our own tiles doesn't sound like much fun.

Well I don't know, it could definitely be pretty fun.

> I don't think packaging with Electron is completely a half-baked idea, but perhaps this could be shelved as a far-off-in-the-future concept.

Yeah, I definitely like the idea of doing it, I just think that we need an excuse/reason to do it.  We need someone to say "hey, I can't do XYZ unless this was a desktop app!", and if that is a compelling enough feature we can dedicate time to overcoming all the obstacles.

So yeah, +1 to shelving until we find that incentive to go that direction.  Any future conversations re: desktop version of Dropchop should take place on this issue.

**Comment by npeihl** [comment]
@alukach Oops. I hadn't seen the Add button. Thanks for pointing it out. I need to keep up better with development.
