### ISSUE TITLE
Clicking on an operation icon numerous time queues multiple executions

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#167]
Each time that an operation icon is clicked, the execution of the operation is staged. When the execution is finally triggered, it runs as many times as operations that were staged (if that makes sense).  See example:

![operation-click-bug](https://cloud.githubusercontent.com/assets/897290/9151579/7067e410-3dc3-11e5-856f-e2337fcf0145.gif)

This occurs between different operation types as well:

![operation-click-bug2](https://cloud.githubusercontent.com/assets/897290/9151594/f3371910-3dc3-11e5-94eb-7e1a31d2166b.gif)

**Comment by mapsam** [comment]
Oh! Whoops. I'll get on fixing this asap.

**Comment by mapsam** [comment]
Man, I'm not sure where to approach this one. Is this fixable in the `AppController.js` or `Menu.js` ?

**Comment by mapsam** [comment]
Heads up, this is no longer an issue in the `alpha` branch! :smile:

**Comment by alukach** [comment]
Looking forward to this brave new `alpha` world!

**Comment by mapsam** [comment]
closed in #176
