### ISSUE TITLE
query overpass api for data?

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#172]
Take a look at this sweetness: https://github.com/perliedman/query-overpass

**Comment by mapsam** [comment]
Why not?

![dropchop-overpassnodes](https://cloud.githubusercontent.com/assets/1943001/9870121/2f6bf8fa-5b3e-11e5-9f4e-9370f9e1ad86.gif)

**Comment by npeihl** [comment]
:+1: I like it!

**Comment by mapsam** [comment]
Mostly kind of done in the `alpha` branch.
