### ISSUE TITLE
overpass API only works for "nodes"

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#189]
It should work for ways/relations as well, but that requires a more intense query [here](https://github.com/cugos/dropchop/blob/master/src/js/ops.file.dropchop.js#L137). Anyone out there with a good understanding of the query formatting?

**Comment by tyrasd** [comment]
If you're interested, I could probably bring in the [query wizard](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Wizard) from http://overpass-turbo.eu/ to work in the overpass data import dialog?

**Comment by mapsam** [comment]
Definitely interested! That seems like a strong move, and would greatly increase the power of our current application.

How can I help you get this started?

**Comment by tyrasd** [comment]
I've finally come around to publish the query wizard code as a separate module: https://github.com/tyrasd/overpass-wizard – see PR #252

**Comment by mapsam** [comment]
:clap: @tyrasd - you are a rockstar.
