### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#190]
@lyzidiamond [once said in a PR](https://github.com/cugos/dropchop/pull/70#issuecomment-100392954) that we should make a `CONTRIBUTING.md` file for this. I think it is time!

**Comment by npeihl** [comment]
:+1: 

I'd suggest using https://github.com/jden/CONTRIBUTING.md as starting point.

**Comment by npeihl** [comment]
Ooh, I like this one, too.

https://github.com/CoralineAda/contributor_covenant.

**Comment by mapsam** [comment]
Thanks for the templates, @npeihl - I really like this [code of conduct](http://contributor-covenant.org/version/1/2/0/code_of_conduct.md) piece from the contributor covenant.

**Comment by mapsam** [comment]
@lyzidiamond I'd like to see some examples of what contributing looks like (specifically non-code related contributions). For example, "drawings of new navigation buttons" or "need help creating example data" or "think about color scheme".

Similarly, defining **what is a contribution?** and making it clear that writing code is not the only path towards a successful contribution. Explaining what a meaningful contribution looks like is important! Things like "asking questions" or "requesting features" are equally powerful as creating those features.

THIS IS WHAT DEMOCRACY LOOKS LIKE

![](http://41.media.tumblr.com/782d478fc64bda292a677433fea133af/tumblr_inline_nmlx4zH0iI1tnn1p2_500.jpg)

**Comment by mapsam** [comment]
Some feedback from @hamhands - he wants to contribute but the issue list is a bit overwhelming. Might be worth maintaining a list of comfortable, small tasks in the file so people can start there?

**Comment by mapsam** [comment]
Also, when we ask for code-related contributions how do we expect people to merge into the proper working branch? Should we always assume contributions come into the `master` branch or do we always state where the current development branch is (i.e. `0.1.1` currently)?

**Comment by mapsam** [comment]
Sorry, big brain dump happening right now:

Talking to someone after the presentation at NACIS, they mentioned they were at the CUGOS Spring Fling last spring and enjoyed being a part of the project during the day, but weren't sure how to continue contributing after the fact. I'm not sure if there is a tangible way to answer this issue, but it reminds me a lot of what @lyzidiamond has been talking about with "post user experience" - how do we establish a positive "post contributor experience"?

**Comment by npeihl** [comment]
This looks like a possible way to encourage new contributors. http://yourfirstpr.github.io/

**Comment by mapsam** [comment]
I've started a `CHANGELOG` in the wiki - so we should include updating this as part of the code-related contributions.

**Comment by alukach** [comment]
Looking at this, I'm wondering if we should just move the `CHANGELOG` (along with install instructions and possible other code-related instructions) into actual files within the repo.  That way, the documentation would reflect the state of the codebase at any given revision (ie, `CHANGELOG` would immediately show which changes are within the current checked out revision).  Part of PR requirements could be adding the information to the `CHANGELOG`.

**Comment by alukach** [comment]
@mapsam regarding beginner-friendly issues, should we start tagging issues as `beginner-friendly` if they don't require significant refactor?

**Comment by mapsam** [comment]
I like the idea of the changelog going into the project files - just didn't want to do it haphazardly without hearing someone else say it first. :+1: for someone to do that if they want. Could be the first flagged `beginner-friendly` issue?

**Comment by mapsam** [comment]
Nice, thanks @alukach!
