### ISSUE TITLE
notifications should have a sticky "close" option

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#193]
Right now notifications disappear after a specified amount of time. This is mostly great, but it would be helpful to allow some to stick to the page until the user clicks to close - especially for errors (i.e. copy/paste the error for reporting bugs)

**Comment by jczaplew** [comment]
The markup for this would probably be something like 

````
<div class='notification'>
  <div class='notificiation-close'>x</div>
  <div class='notification-body'>
        Text goes here
  </div>
</div>
````

In the past for something like this I've used [Mustache](https://github.com/janl/mustache.js/) but it seems silly to add another dependency for something so simple. Any ideas on how to best do this without adding another dependency?

**Comment by mapsam** [comment]
I've been building a lot of the HTML just with jQuery and appending it to the `dc.$elem` object. Here is the [notification HTML](https://github.com/cugos/dropchop/blob/master/src/js/notify.dropchop.js#L7-L11) and we'd want to add a `.on('click')` to the *close* element, similar to the way we are [adding events on the layerlist elements](https://github.com/cugos/dropchop/blob/master/src/js/layerlist.dropchop.js#L53-L57).

I'm not sure if this is legit at all, but that's how it's working now! I agree on not including Mustache, mostly because there are so many big dependencies it would be nice not avoid including more for now.
