### ISSUE TITLE
State preservation with URL-loaded layers

### ISSUE THREAD

**Issue by jczaplew** [cugos/dropchop#194]
If the layer is loaded from a URL that contains an ampersand, it is not parsed correctly.

For example `?url=https://macrostrat.org/api/v2/paleogeography?age=250&format=geojson_bare` will request `https://macrostrat.org/api/v2/paleogeography?age=250` because the search is split on the ampersand.

**Comment by mapsam** [comment]
@jczaplew it might be worth writing an updated test for this, but definitely fixed in #195!
