### ISSUE TITLE
Writing test for dc.util.xhr

### ISSUE THREAD

**Issue by npeihl** [cugos/dropchop#196]
While working on writing tests for #191, I noticed dc.util.xhr didn't have tests written yet. I've tried my hand at writing a test using [sinon.useFakeXMLHttpRequest](http://sinonjs.org/docs/#useFakeXMLHttpRequest). But I ran into issues with [this line](https://github.com/cugos/dropchop/blob/master/src/js/util.dropchop.js#L33). I'm still rather new to this, so I'm having trouble figuring out what `callback.bind(this, xhr)` is doing. Can you educate me? 

Thanks.

**Comment by mapsam** [comment]
@alukach is going to be your man here - I think I lost a lot his tests when bringing in the new updates so we may have an XHR sinon test written already

**Comment by alukach** [comment]
@npeihl The reason that it is written that way is a bit fuzzy in my memory.

Are you familiar with the [`bind`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) method? In short, it returns the function that `.bind()` is run on with a copy of itself, but with the `this` variable assigned to the object you provide and then optionally any future arguments passed in `bind()` will be passed to the function when it's called.  Thanks to @mapsam's restructuring, all of the noodling around with overriding `this` args isn't really necessary anymore. However, looking at the code it appears that an `XMLHttpRequest()` object passes an `xhrEvent` object to the `onload` handler by default.  That event isn't particularly useful, it doesn't have any of the good stuff that we would want when handling the results of an AJAX request (for example, the `responseText`). To get around that, we `bind` the `xhr` object to the callback function, which will have lots of useful information populated on the object at the time of a completed AJAX request. That way, at time of callback, we can access the results data.

At least I think that's what's going on. I'm not an expert on doing AJAX requests without jQuery, there may be a much more sane way to do the same thing.

**Comment by npeihl** [comment]
Thanks @alukach. That makes sense. Since we now have jQuery as a dependency, would it make sense to use `$.get()` rather than writing our own `XMLHttpRequest`? cc @mapsam

**Comment by mapsam** [comment]
I think that's a great idea - no reason to overcomplicate things since jQuery will do it for us. What do you think @alukach?

**Comment by alukach** [comment]
@npeihl yeah, I think we should just use the jQuery methods if available.  It was kind of fun building out DC without jQuery (or Backbone or Angular or React or ...), but now that we've started using it, it seems like we should just squeeze out as much utility out of it as possible (assuming that performance doesn't suffer).

**Comment by alukach** [comment]
@mapsam regarding `$.get` in a utility vs ad-hoc, hard to say, I'd probably vote for going ad-hoc.  It's nice to use utility functions to enforce best-practices, but maybe unnecessary if it's a single line pass-through.

**Comment by mapsam** [comment]
> It was kind of fun building out DC without jQuery

It pains me too :sob: but it's making the barrier to entry a lot lower for people, which is a big :heavy_plus_sign:

**Comment by npeihl** [comment]
I swapped in the `$.ajax` function in #191 [here](https://github.com/cugos/dropchop/pull/191/files#diff-7a0f50bffcd8768b3ceb1b4f28d4c275R52). Not sure yet if/how I want to test this. Seems like Sinon's [fakeServer](http://sinonjs.org/docs/#fakeServer) should do it, but I've been having trouble with some prelim runs with it.

**Comment by mapsam** [comment]
Since we are no longer use a custom `xhr` implementation, can we close this @npeihl?

**Comment by npeihl** [comment]
@mapsam: Yup. Closing.
