### ISSUE TITLE
turn "load data" buttons into a single option

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#197]
With the incorporation of @npeihl's Arc feature service we are going to have at least 5 ways to add data to the app: `local files`, `url`, `gist`, `overpass`, and `feature service`. That's getting to be a lot of options on the left-hand bar, and the icons aren't going to be very versatile as we get into more company-specific options.

I propose turning all of the buttons into a "load data" button that has specific ways to load data that can be selected in the popup (or something). Might require developing a new menu type, or further developing the `form.dropchop.js` file to allow for form responsiveness based on what the user is selecting, but I think it will clean up the sidebar quite a bit.

**Comment by npeihl** [comment]
:+1: Perhaps a radio button control like QGIS uses? 

![2015-10-19 17_01_03-add vector layer](https://cloud.githubusercontent.com/assets/1638483/10594547/13e2a56a-7683-11e5-9a6c-a90715f3b58a.png)

**Comment by mapsam** [comment]
I like that idea. Though I'd like people to be able to see the options right away, without having to click the upload button to see. What do you think about starting with a quicker option right now, which is just making some collapsable menus on the left-hand side - when you hover over "import" you see the buttons for each type?

I'll get a mockup of it going and we'll see how it looks.

**Comment by mapsam** [comment]
Alright, here is a mockup of what I'm thinking about for now:

![dropchop-collapseablemenu](https://cloud.githubusercontent.com/assets/1943001/10656731/dca2cac0-7836-11e5-9a45-67e6b4102d39.gif)

What do you think?

**Comment by mapsam** [comment]
This requires an added level of separation for the menu building, since we need all of our options to be referenced from the top level of `dc.ops.file[action]` - so I put together a quick `leftMenuSetup` array that looks like this:

```javascript
var leftMenuSetup = [
  {
    name: 'import',
    icon: '<i class="fa fa-plus"></i>',
    actions: [
      'upload',
      'load-url',
      'load-gist',
      'load-overpass',
      'location'
    ]
  },
  {
    name: 'Save',
    icon: '<i class="fa fa-floppy-o"></i>',
    actions: [
      'save-geojson',
      'save-shapefile'
    ]
  },
  {
    name: 'Geo Actions',
    icon: '<i class="fa fa-wrench"></i>',
    actions: [
      'extent',
      'expand',
      'combine',
      'rename',
      'remove',
    ]
  },      
  'info'
];
```

This is the base of our menu order, instead of it being coupled to the actual order of the `dc.ops.file`. This is starting to look a bit like the way we used to build the menus in dropchop, which required multiple options. Basically right now, if an element in the above array is an `object` we assume it is a collapseable menu and loop through the `object.actions` to create more buttons.

**Comment by jczaplew** [comment]
Looks great! It's exactly what I was imagining.
