### ISSUE TITLE
TopoJSON

### ISSUE THREAD

**Issue by jczaplew** [cugos/dropchop#201]
Add the ability to drag and drop TopoJSON, import it from a URL, and export to TopoJSON. This will obviously require the addition of one dependency (TopoJSON), but definitely increases interoperability.

UI-wise I don't think anything should change - it should be very easy to figure out if a file is Geo or TopoJSON, i.e. something like

````
if (data.type === "FeatureCollection") {
  // GeoJSON
} else if (data.type === "Topology") {
  // Topojson, convert to GeoJSON
} else {
  // Hmmm...
}

````

**Comment by mapsam** [comment]
Great idea. Adding a dependency for this is totally acceptable!

**Comment by jczaplew** [comment]
In order to export as TopoJSON, a UI change of some sort will be required. I see two options:

+ Add another button
+ Collapse `Save as GeoJSON` and `Save as Shapefile` down into a single button/menu/modal and add TopoJSON export there.

I'm partial to the latter option. Perhaps a general `Save` button with a submenu that pops out with the three options?

**Comment by mapsam** [comment]
Agreed on the submenu! Seems like a super useful UI component to incorporate as we add new options.

**Comment by jczaplew** [comment]
Export as TopoJSON can be added once #208 is merged

**Comment by mapsam** [comment]
Merged. Ready to roll.

**Comment by jczaplew** [comment]
Turns out saving as topojson isn't as easy as I expected https://github.com/mbostock/topojson/issues/208

**Comment by mapsam** [comment]
Bummer :frowning: - what about at least getting TopoJSON to import? [leaflet-omnivore](https://github.com/mapbox/leaflet-omnivore) would be a solid addition IMO.

**Comment by jczaplew** [comment]
See #212 ;-)

**Comment by mapsam** [comment]
:clap:
