### ISSUE TITLE
feature request: Zoom to layer extent on click

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#205]
From https://twitter.com/jlivni/status/654347632576368640

**Comment by alukach** [comment]
So what do you see this as being? I can imagine building out right-click menus for each layer, but that doesn't sound very _dropchoppy_.  We can add a little magnifying class on hover next to the Copy / Delete icons: 

![image](https://cloud.githubusercontent.com/assets/897290/10670045/d5cfb130-78a0-11e5-9b53-bf3aab03f375.png), 

But I don't know how sustainable that is.  As mentioned in #130, I see adding the ability to visually style each layer as well.  We wouldn't want that set of icons to get too busy.

Thourhgts?

**Comment by mapsam** [comment]
I'm not entirely sure. I agree that adding it as a specific option would start to make things a bit cluttered. Might be worth exploring a layer options menu (right click or otherwise, similar to #197) sooner than later so we can add a number of functions to it.

I don't think we should pan/zoom just when the user clicks on a layer though, since that could be a LOT of movement, which could be disorienting. Maybe load to the extent of layers created through operations?

**Comment by alukach** [comment]
Yeah, clicking the layer name is for selecting, not for zooming.  To me, that feels natural and expected.  Above I was saying that it would be another function run on a layer (similar to copy/delete), as either an icon that kicks off the zoom or a right-click menu option.  Or did I misunderstand what you were just saying above?

**Comment by alukach** [comment]
Actually, one important thing to distinguish: when we are saying "click on layer", are we talking about the layer representation in the layerlist or the layer representation on the map?  On layerlist, that currently selects; on map view, that seems to bring up additional metadata about the layer.

**Comment by mapsam** [comment]
Good point! I was talking about layerlist, which I agree should be reserved for just selection. Clicking the map layer up for discussion.

**Comment by jlivni** [comment]
Maybe double clicking to zoom to extent?  But given the other related layer ideas perhaps a right click menu is a better long term plan.

**Comment by mapsam** [comment]
Ohhh double clicking.. that's something that hasn't come up yet. Seems like double clicking would be more of an easter-egg/power-user component, rather than a first-time user UI piece. Worth keeping that in mind for other things as well.

This reminds of an idea @bgolder brought up, where we could building hot-keys for the entire system, allowing for quick power-user experience.

What's the word for UI that isn't experienced until you do it by accident? Double clicks fit in that category. I honestly had no idea there was a double click event binder until now. https://api.jquery.com/dblclick/

**Comment by mapsam** [comment]
Seems like leaving the zoom to layer action as a right-click/menu option is best for now. Going to leave it to #211 and @alukach to conclude.
