### ISSUE TITLE
dragging shapefile .zip doesn't load, just hangs

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#206]
Trying out this shapefile, and it just sits loading forever without any console errors.

ZIP: https://drive.google.com/open?id=0B0E-VGwUGzsSaUtodVVEaWxZWVU

**Comment by jczaplew** [comment]
My guess is that shapefile-js/proj4js doesn't recognize that specific projection and chokes. I'll investigate.

**Comment by jczaplew** [comment]
Do you think we can consider this closed? It's not exactly a satisfying solution, but I was unable to figure out what projections shapefile-js supports ( [issue here](https://github.com/calvinmetcalf/shapefile-js/issues/50) ). Ideally we would make it work with any projection, but I'm not sure what the scope of that job entails.

**Comment by mapsam** [comment]
Yah, let's close for now!
