### ISSUE TITLE
Don't uglify on dev builds

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#213]
I've been disabling the `.pipe(uglify())` of the Gulpfile to make debugging easier in Chrome devtools.  Would be nice to have this done automatically during dev builds.  I suppose this could be based off of a `env` variable, be the default behavior for the `gulp` command, create a new gulp command (`gulp dev`), or have some flag passed in to the gulp command (`gulp --no-uglify`). I think I'd prefer for it to be the default behavior.

**Comment by mapsam** [comment]
Hm... there is a site map built with `.pipe(sourcemap.write())` that should lead back to where errors are coming from. I haven't run into any issues thus far with it working this way. Is the sourcemap not working on your end?

**Comment by npeihl** [comment]
Sourcemap has been working fine for me on Firefox.

**Comment by alukach** [comment]
The sourcemap _worked_ in that it appears correct in the source, but all the variables are renamed which is a bit of a pain during development:

![image](https://cloud.githubusercontent.com/assets/897290/10776688/3afc192c-7cd9-11e5-8a29-e41d8732f332.png)

Maybe there's a pro-tip that I'm missing to compensate for this?  I'm using Chrome 46.0.2490.71 (64-bit).

**Comment by mapsam** [comment]
whoa that's weird, I haven't seen them renamed at all in my browser.

**Comment by alukach** [comment]
I experience the same on my work machine on both Chrome:
![image](https://cloud.githubusercontent.com/assets/897290/10794056/f574a07e-7d58-11e5-8890-6b06273f1aa6.png)

and Firefox:
![image](https://cloud.githubusercontent.com/assets/897290/10794146/58ec3bbc-7d59-11e5-8a81-ab8ff476348d.png)



Are you sure you guys don't experience this?

**Comment by mapsam** [comment]
Hm, I guess I've never used the scope feature and always tend to debug straight in the console. Looks like scope is truncated just like yours:

<img width="315" alt="screen shot 2015-10-28 at 10 06 21 am" src="https://cloud.githubusercontent.com/assets/1943001/10796512/b2529834-7d5b-11e5-8ed9-c6d412b1cf82.png">

But `dropchop` object is what I use so I've never had a problem: 
<img width="688" alt="screen shot 2015-10-28 at 10 06 47 am" src="https://cloud.githubusercontent.com/assets/1943001/10796511/b24b7270-7d5b-11e5-9599-b38f4fd8879b.png">

**Comment by mapsam** [comment]
*/me wonders if he should start using this scope feature*

**Comment by npeihl** [comment]
Looks like there's an [issue](https://code.google.com/p/chromium/issues/detail?id=327092) logged with Chrome for this type of situation. I wonder if Firefox has one, too.

**Comment by mapsam** [comment]
The sourcemap is generating file/line specific errors as expected right now - going to close this!

<img width="386" alt="screen shot 2016-07-30 at 2 42 49 pm" src="https://cloud.githubusercontent.com/assets/1943001/17277472/99cd7fa0-5711-11e6-92d4-752db8d11b71.png">
