### ISSUE TITLE
Support Routing

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#215]
Would be great to get support for Routing in DC.  

Example use-case:

> A map that, when opened, loads a users location, queries the Overpass API for pizza restaurants within 2 miles, and then provides a route via bicycle to get user there.

That goal is a bit of a ways out, but would be nice to have.  I'm agnostic to which routing tools to use.  Any ideas?  [Mapbox](https://www.mapbox.com/developers/api/directions/)?  Any of [these](http://wiki.openstreetmap.org/wiki/Routing/online_routers)?

**Comment by mapsam** [comment]
I think routing is out of scope at this point in dropchop's life. If routing were to be built in, using an [OSRM](https://github.com/Project-OSRM/node-osrm) endpoint from [Mapbox](https://www.mapbox.com/directions/) would be the way to go.
