### ISSUE TITLE
TopoJSON not encoding correctly?

### ISSUE THREAD

**Issue by jczaplew** [cugos/dropchop#220]
Getting wacky geometries....

**Comment by jczaplew** [comment]
<img width="457" alt="screen shot 2015-10-27 at 17 13 59" src="https://cloud.githubusercontent.com/assets/1739551/10774268/2690996e-7cce-11e5-9ddf-36122fd45817.png">

**Comment by mapsam** [comment]
whoaaaaaaaaaa

**Comment by jczaplew** [comment]
This wasn't happening yesterday...no idea what changed.

**Comment by jczaplew** [comment]
Related: can we rebase master to clean up my slop some how?

**Comment by mapsam** [comment]
Hm, I guess we could rebase from our local and push straight into master? It's a protected branch so not sure if that's possible anymore.

**Comment by mapsam** [comment]
Possible quick fix, just remove `save-topojson` from the menu?

**Comment by jczaplew** [comment]
See #221 for a quick fix.

**Comment by mapsam** [comment]
Closing this after #221 merged.
