### ISSUE TITLE
Files saving with wrong name

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#233]
![save_oddity](https://cloud.githubusercontent.com/assets/897290/11024781/c69d7f54-8650-11e5-8e14-7a70fb5751bc.gif)

If I highlight 5 files and save them as GeoJSON, TopoJSON, or Shapefile, that number of files is downloaded but each is named matching the last file in selection.

**Comment by mapsam** [comment]
Duplicate of #184

**Comment by mapsam** [comment]
Sorry, didn't mean to close.

**Comment by alukach** [comment]
Yeah, you're right, this is actually #184, didn't realize but each file downloaded contains the same data. Closing.
