### ISSUE TITLE
Need documentation for "Uploading Files"

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#234]
We need documentation in README.md for how a user can upload files to Dropchop (drag-drop & upload button).

**Comment by alukach** [comment]
@mapsam, you added this functionality, care to add a quick bit of writeup?

**Comment by mapsam** [comment]
Yup, I can do this. Can you give an example of the perspective you'd like this written from? How technical should it be?

**Comment by alukach** [comment]
I was thinking pretty non-technical. Basically, something like "you can drag and drop files or use the icon to select files to upload. Here are the supported file types: ...  Note that no data will actually be put online when uploading files".

**Comment by alukach** [comment]
Closed via #244 and #243
