### ISSUE TITLE
Need documentation for adding data via Feature Service

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#238]
We need documentation in README.md for how a user can add data via ArcGIS Server Feature Service to Dropchop.

**Comment by alukach** [comment]
@npeihl you added this feature, care to take a swing at adding some documentation?

**Comment by npeihl** [comment]
I'm on it. :notebook_with_decorative_cover:

**Comment by alukach** [comment]
@jonahadkins threw down a basic one-sentence write-up and gif.  If you're up to it, I think there's still room to describe the different fields and possible gis server requirements of the feature.
