### ISSUE TITLE
Travis CI builds failing

### ISSUE THREAD

**Issue by nickpeihl** [cugos/dropchop#246]
Over in PR #245 I've noticed my Travis CI build is failing. This struck me as strange since it was a documentation only update. The [build log](https://travis-ci.org/cugos/dropchop/builds/91055157) says the error is `RangeError: Maximum call stack size exceeded` related to `uglify-js`. 

I found the error mentioned in an [Uglify-JS issue](https://github.com/mishoo/UglifyJS2/issues/414) which was reportedly resolved by updating Uglify-JS. So I tried updating gulp-uglify to v1.5.1 but still received the same error on my machine.

I wondered if maybe it was related to the Node.js version, so I dramatically switched to Node v5.0.0 (the latest stable version) and tried again. This time it worked without error.

Has anyone else experienced this issue?

**Comment by mapsam** [comment]
I've noticed the Travis CI builds being pretty iffy as well. Would be interested in exploring a solution!

**Comment by mapsam** [comment]
Fixed in #257 by lessening `vendor.js` build and upgrading to node 4.x
