### ISSUE TITLE
Support 'ctrl' key for multiple layer select in Ubuntu

### ISSUE THREAD

**Issue by powersa** [cugos/dropchop#249]
Use control c to select multiple layers that aren't next to each other.

**Comment by alukach** [comment]
Is this not what currently happens? By holding control, I believe you can
select multiple layers within the layer list regardless if they're
contiguous or not. Adding 'shift' will select all layers between current
selection and clicked layer.

**Comment by mapsam** [comment]
Indeed. Some screenshots of what works for me:

Using `command` key on Mac
![dropchop-selection-command](https://cloud.githubusercontent.com/assets/1943001/11638056/a7032762-9cd9-11e5-866f-418fea55c006.gif)

Using control key on mac opens menu
![dropchop-selection-control](https://cloud.githubusercontent.com/assets/1943001/11638057/a703d86a-9cd9-11e5-8212-2ba9746c0b88.gif)

Using shift selects anything in between
![dropchop-selection-shift](https://cloud.githubusercontent.com/assets/1943001/11638058/a7049fca-9cd9-11e5-9f98-c90f475ee600.gif)

**Comment by mapsam** [comment]
@powersa are you using a PC? I wonder if special selections are different between Mac and PC

**Comment by powersa** [comment]
Woo, this might be something really specific to my setup. I'm running ubuntu 14.04 on a Lenovo ThinkPad T440s. The ctrl key doesn't work for me. But my computer does have a windows key that lets me select non-contiguous layers. 

Anybody else on ubuntu able to test?

**Comment by mapsam** [comment]
Hm! Interesting. Let's test this on Wednesday at the sidecar.

**Comment by powersa** [comment]
sounds great, thanks @mapsam

**Comment by alukach** [comment]
@powersa I use Ubuntu at work but don't experience this issue. Which browser are you using?  It's strange that <kbd>ctrl</kbd> key doesn't do its magic on your system.

**Comment by alukach** [comment]
Ah, disregard my above comment, the <kbd>ctrl</kbd> doesn't work on my Ubuntu machine! Looks like we've got a legit bug on our hands, thanks @powersa. (For the record, using Chrome Version 46.0.2490.86 (64-bit) on Ubuntu 14.04).

**Comment by powersa** [comment]
oh my oh my. such relief. thanks for following up y'all.

**Comment by mapsam** [comment]
Will take a look at the CUGOS sidecar tomorrow night :+1:

**Comment by alukach** [comment]
Oops, didn't mean to steal any thunder from tomorrow's sidecar, but I think #250 should resolve the bug.

**Comment by powersa** [comment]
haha, sidecar must go on!

**Comment by alukach** [comment]
@powersa I merged in #250, can you test this out when you get a chance (I forgot to test at work)? On a Mac, the <kbd>ctrl</kbd> key + clicking acts as a right-click, which I think is caught by Dropchop's right click handler and thus the multiple-select logic isn't fired (this is a guess).

**Comment by alukach** [comment]
Testing this on my Ubuntu machine seems to work.  Will close for now.
