### ISSUE TITLE
Layers are starting to generate on layerList out of nowhere after operations complete

### ISSUE THREAD

**Issue by svmatthews** [cugos/dropchop#64]
Look at the layers that come out of the union in this gif:

![dnc-bufferz](https://cloud.githubusercontent.com/assets/1943001/7458748/c9a8a8ac-f24b-11e4-99ee-ea149916724d.gif)

`sf.geojson` and `east.geojson` are duplicated. Wtf!? Probably a result of some of the work on #63

**Comment by svmatthews** [comment]
Diving into this, the `map` object doesn't even show these layers as existing. WTF!

**Comment by alukach** [comment]
This bug still appears to be present.

![Uploading bug.gif…]()

**Comment by svmatthews** [comment]
It's confusing me so much!

**Comment by mccombsp-kingco** [comment]
I'm getting some layers duplicated when I add a new layer. I think this is the same bug.

**Comment by svmatthews** [comment]
Looks like @alukach has come upon a solution in #107

**Comment by svmatthews** [comment]
Closing this issue, now that #107 has been added
