### ISSUE TITLE
Add your own base layer

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#74]
Now that @lyzidiamond added the feature to switch base layers, it would be awesome to implement a custom layer. This would essentially allow the user to input their own Mapbox tile ID and key?

@lyzidiamond do you know if this would require a key or would the ID be sufficient?

**Comment by lyzidiamond** [comment]
We could handle the map views with our own token and just as for ID, or we can ask them for an ID and a token. CartoDB asks for both when you add a Mapbox layer... it depends. We can talk about it.
