### ISSUE TITLE
Update readme gif

### ISSUE THREAD

**Issue by lyzidiamond** [cugos/dropchop#77]
Because those example bars bother me ;)

**Comment by svmatthews** [comment]
Hehe.

**Comment by svmatthews** [comment]
This has been at least fixed with a new gif that doesn't have "EXAMPLE" tiles. Feel free to update or close this issue, @lyzidiamond!

**Comment by lyzidiamond** [comment]
:+1:

**Comment by svmatthews** [comment]
Ok apparently I'm blind and added a new gif with example tiles. Doh!
![doh](https://cloud.githubusercontent.com/assets/1943001/7780859/a87be390-00b2-11e5-8513-136588efadac.gif)
