### ISSUE TITLE
incorporate browserify?

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#8]
@thebigspoon I'm curious if you'd want to use browserify here or stick with using the Grunt [`wiredep`](https://github.com/stephenplusplus/grunt-wiredep) for loading in all of our bower components?

**Comment by svmatthews** [comment]
After #19 we are removing bower from the equation and going to roll with some quick CDNs and begin working on incorporating browserify for module use.

**Comment by svmatthews** [comment]
This is coming up as an issue as people begin looking at #11

**Comment by alukach** [comment]
What does @aaronr think about this?

Why was it that we decided to table browserify in the first place?  I don't quite recall.  I do like the idea of writing this all node-like in the event that we ever want to make an offline-friendly downloadable DNC.

**Comment by thebigspoon** [comment]
@svmatthews @alukach @aaronr 
I think the easiest solution here is just use `browserify` to require the third-party modules you need to require and then expose/tag them to the `L.DNC` namespace. You'll just have to ensure that the browserify build happens at the end so the `L.DNC` namespace is created.

```javascript
var shape_package = require('shapefile-lib-thing');

L.DNC.ShapeUtils = shape_package; 
```
