### ISSUE TITLE
_unCollect should run on files added, rather than executed

### ISSUE THREAD

**Issue by mapsam** [cugos/dropchop#92]
Right now if someone adds a `featureCollection` of a single feature from their desktop, it stays the same. When adding the feature to the map, we should `_unCollect()` instead of that function only existing withing `GeoExecute.js`

**Comment by svmatthews** [comment]
Similarly, what happens if turf requires a feature collection but the object is only a feature?

**Comment by svmatthews** [comment]
Okay, another thought is to actually turn everything into a `featureCollection`, and then run operations recursively if turf only accepts a `feature` at a time. Thoughts @alukach?

**Comment by alukach** [comment]
Haven't thought too much about this, but something irks me about changing data automatically upon upload.  I like my data to stay pure, unadulterated, unless absolutely necessary.

**Comment by mapsam** [comment]
I think you are correct, @alukach doing this on load isn't a good idea. Might be a fun extra function to create, though - "Turn feature collection into unique features" action.
