### ISSUE TITLE
drag and drop geojson

### ISSUE THREAD

**Issue by bricker0** [cugos/dropchop#98]
I couldn't drag and drop the geojson file from my downloads folder, so I moved to desktop and dragged it from there...just so you know

**Comment by alukach** [comment]
Odd.. which operating system and browser are you using?  Did the browser dim when you hovered the file over the browser?  Can you repeat this error?

**Comment by svmatthews** [comment]
This was a really weird instance - I haven't been able to replicate it at all. It was a OSX and Chrome (was watching it happen and forced @bricker0 to submit the issue :stuck_out_tongue_closed_eyes:) The browser was dimming, too.

My only guess is that it wasn't recognized as a `.json` file type for some reason. It was a geojson dowloaded from geojson.io using the SAVE > GEOJSON menu option.

**Comment by svmatthews** [comment]
This happened to me the other day. And I forgot to see what was going on. :ghost: issue!

**Comment by alukach** [comment]
So, at current time, this seems like a user-workflow issue that may be out of our hands. Going to park this unless it's possible for us to develop something to avoid this in the future.
